apiVersion: v1
kind: Service
metadata:
  name: backend-estabelecimento-svc
  namespace: backend-estabelecimento
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-estabelecimento-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080