name: 2 - [FEAT] Execute Tests

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "develop"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Tests
        run: mvn -B test --file ./pom.xml