name: 2 - [FEAT] Terraform Format and Validate

on:
  pull_request:
    branches:
      - "develop"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Tests
        run: mvn -B test --file ./pom.xml